{{- if .Values.go-app.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: go-app-stable
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: go-app
  ports:
  - port: {{ .Values.go-app.service.port }}
    targetPort: 80
    protocol: TCP
---
apiVersion: v2
kind: Service
metadata:
  name: go-app-canary
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: go-app
  ports:
  - port: {{ .Values.go-app.service.port }}
    targetPort: 80
    protocol: TCP
{{- end }}