{{- if .Values.go-app.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: go-app-service
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
{{- end }}
